### 자산 추가 POST
POST http://localhost:8080/asset
Content-Type: application/json

{
  "c_cert": "appuser",
  "id": "asset101",
  "c_color": "blue",
  "c_size": "100",
  "c_owner": "student",
  "c_value": "10000"
}

### 자산 조회 GET
GET http://localhost:8080/asset?c_cert=appuser&id=asset101

### 자산 전송 POST
POST http://localhost:8080/asset/tx
Content-Type: application/json

{
  "c_cert": "appuser",
  "id": "asset101",
  "c_owner": "KIM"
}


### 자산 이력 조회 GET
GET http://localhost:8080/asset/history?c_cert=appuser&id=asset101